tablica=[12,6,4,9,3]
tablica[0]="************"
tablica[1]="******"
tablica[2]="****"
tablica[3]="*********"
tablica[4]="***"
print("12:",tablica[0])
print("6:",tablica[1])
print("4:",tablica[2])
print("9:",tablica[3])
print("3:",tablica[4])